
export const GET_POST_LIST = 'GET_POST_LIST';
export const SAVE_POST = 'SAVE_POST';
export const DELETE_POST = 'DELETE_POST';
export const UPDATE_POST = 'UPDATE_POST';

export const GET_INTERESTS_LIST = 'GET_INTERESTS_LIST';

export const GET_SELF_POSTS_LIST = 'GET_SELF_POSTS_LIST';
export const LIKE_POST = 'LIKE_POST';
export const UNLIKE_POST = 'UNLIKE_POST';
export const GET_POST_DETAILS = 'GET_POST_DETAILS';
export const REMOVE_POST_DETAILS = 'REMOVE_POST_DETAILS';

export const POST_COMMENT = 'POST_COMMENT';
export const LOGOUT_USER = 'LOGOUT_USER';